### PR TITLE
Ensure PHP client parses boolean and double values correctly

### PR DESCRIPTION
**Pull request by sbrattla**
Right now the PHP client parses booleans as strings and double/floats as integers. This PR refactors that part to ensure that booleans are parsed as actual boolean types, and doubles/floats are parsed as floats.

### CODE REVIEW

**Comment by sbrattla** [comment]
@stoicflame any chance this one can make it into the next release?

**Comment by stoicflame** [comment]
Yes, it's already merged. It'll be in the next release.

**Comment by sbrattla** [comment]
@stoicflame it seems to me that this patch is part of the 2.12.1 release?

https://github.com/stoicflame/enunciate/blame/f66f3ecf4fcb2353b6c87d74b1fa02063f319955/php-xml-client/src/main/java/com/webcohesion/enunciate/modules/php_xml_client/ClientClassnameForMethod.java#L68

**Comment by stoicflame** [comment]
Yes, it looks like that's correct. I don't know why I didn't mark it as such.

**Pull request merged**
