### PR TITLE
option to retain original resource names

### PR DESCRIPTION
**Pull request by jskovjyskebankdk**
Allow the original resource method names to be retained instead of using synthetic (very long) method names.

Again, this is done to make Swagger generation prettier. I am not sure how the slug() method is otherwise used, so am unsure of what other impact using the option might have.

I also changed the XSD, but it was already invalid (as per http://www.utilities-online.info/xsdvalidation/). I hope my change is valid (not much of an XSD hacker).

If accepted, the JAX-RS wiki documentation should be amended with:

keepOriginalMethodNames|(Since 2.10) Whether to keep original resource method names. Default false.

### CODE REVIEW

**Comment by stoicflame** [comment]
I'm still not understanding the problem that this PR is trying to solve. The method slug shouldn't be displayed anywhere... are you seeing otherwise?

**Comment by jskovjyskebankdk** [comment]
The original code generates swagger.json fragments like this:

```
      "get" : {
        "tags" : [ "SubEnvironmentRestResource" ],
        "description" : "",
        "operationId" : "resource_SubEnvironmentRestResource_getSubEnvironment_GET",
        "produces" : [ "application/xml" ],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "required" : true,
            "type" : "integer",
            "format" : "int64",
            "description" : ""
          }
        ],
        "responses" : { 
...
```

When using swagger's code generation, this results in classes with methods like:

```
    @GET
    @Path("/v1-0/subenvironments/{id}")
    @Produces({ "application/xml" })
    @ApiOperation(value = "", tags={  })
    public XmlNs0SubEnvironmentDTO resourceSubEnvironmentRestResourceGetSubEnvironmentGET(@PathParam("id") Long id);
```

And I much prefer it to be readable as:

```
    @GET
    @Path("/v1-0/subenvironments/{id}")
    @Produces({ "application/xml" })
    @ApiOperation(value = "", tags={  })
    public XmlNs0SubEnvironmentDTO get(@PathParam("id") Long id);
```

as it will be, if the API author was just calling it get.



Since you did not realize the string ended up there (or its impact), maybe using the slug is wrong?
I must admit that I did not read enough of the code to see what the slug was intended for - I just followed the lead back from the swagger backend.

**Comment by stoicflame** [comment]
The slug is used to uniquely identify the method among all other methods.

This is aligned with the Swagger definition of the `operationId`, which is defined as:

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API.

So my biggest concern about allowing use of the resource method name is that it's not unique and it might break some links.

According to swagger-api/swagger-codegen#639, the operationId is optional. And at swagger-api/swagger-codegen#651, they updated the code to make more conventional use of the `operationId`. What if we adjusted the slug to accommodate those style conventions?

**Comment by jskovjyskebankdk** [comment]
Ah! My bad.

The code worked fine with the swagger code-gen application.

I had not looked at the swagger spec.
I just tested the generated swagger.json in http://editor.swagger.io/#/ and it does complain about the code being invalid.

So I'll just close this issue. I will try to find some other way to make the code-gen behave - within spec :)

**Pull request closed without merging**
