### PR TITLE
jackson: ignore wildcardMember if annotated with @Ignore

### PR DESCRIPTION
**Pull request by panchenko**
Feels logical and more explicit than member deprecation.

### CODE REVIEW

**Comment by stoicflame** [comment]
So this will only exclude the wildcard from the documentation example where `@Ignore` is designed to be used for excluding the member entirely. I'd rather see the `@Documentation(exclude=true)` annotation be honored for this particular case.

**Comment by panchenko** [comment]
I've added also the `@DocumentationExample.exclude` check. However that's the only usage of `wildcardMember`, so `@Ignore` also applies. Or do you think it's completely not appropriate here?

**Comment by stoicflame** [comment]
There _are_ other usages of `wildcardMember`, but they're in freemarker templates, so it's harder to catch. For example, the generated JSON client will include a wildcard member if there's a wildcard member in the source Java object. So I'm saying that `@Ignore` should be universal and `@DocumentationExample.exclude` is limited to the generated example.

Also, I'd like to see the same logic applied to the `jackson1` module.

**Comment by panchenko** [comment]
Thanks for the details, I've updated this PR, will file the `@ignore` check separately.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).

**Pull request merged**
