### PR TITLE
Security definitions in swagger

### PR DESCRIPTION
**Pull request by fhm84**
As a first (of course, very basic) version adding security definitions, here a suggestion for an implementation.

### CODE REVIEW

**Comment by stoicflame** [comment]
Please rebase onto the latest `master` branch.

**Comment by fhm84** [comment]
Done (hopefully merge instead of rebase is also fine?).

**Comment by stoicflame** [comment]
Pushed at 3a32929d314982d742422104a9c1489db9985d0c

**Comment by stoicflame** [comment]
[Enunciate 2.18.0](https://github.com/stoicflame/enunciate/releases/tag/v2.18.0) has been released.

**Pull request closed without merging**
