### PR TITLE
Javascript client

### PR DESCRIPTION
**Pull request by justincy**
This is for #378. It's not 100% finished. I'm throwing it out there early for comments.

I still need to add a variable for configuring what name the library gets mounted at when included as a browser global.

I upgraded freemarker so that I could use the `[#sep]` tag.

Todo:

* [x] Add configuration variable for the global name of the library when used as a browser global.
* [x] Write the library description

### CODE REVIEW

**Comment by justincy** [comment]
Any tips on how to add the configuration variable? I see code like `this.config.getString("[@slug]")` but I don't know where that config originates from.

**Comment by stoicflame** [comment]
Cool! I'll take a look.

**Comment by stoicflame** [comment]
> Any tips on how to add the configuration variable? I see code like `this.config.getString("[@slug]")` but I don't know where that config originates from.

Each module gets assigned it's configuration element based on the module name. So if you called `this.config.getString("[@slug]")` in the `JavaScriptClientModule` it would get the value of the `@slug` configuration attribute:

```
<enunciate>
  <modules>
    <javascript-client slug="myslug"/>
```

**Comment by justincy** [comment]
@stoicflame Thanks for the guidance. 

It's ready for review now. Two important notes:

1. It uses a UMD loader which supports AMD, CommonJS and browser globals. In other words, the library can be used in Node, used with RequireJS, and be used in the browser.
2. It uses ES6 classes which don't yet have universal support. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Browser_compatibility and https://kangax.github.io/compat-table/es6/

**Comment by stoicflame** [comment]
Gorgeous. 

Thanks for the patch; finally got around to reviewing it.

(FYI, it may be a little while before this gets applied to the GEDCOM X project. We're still using Enunciate 1 over there, but the move to Enunciate 2 is on the backlog.)

**Comment by justincy** [comment]
Thanks.

I'm not waiting on this being applied to GEDCOM X. I already started my own library for that: https://github.com/rootsdev/gedcomx-js

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).

**Pull request merged**
