### PR TITLE
Add method generate(org.codehaus.doxia.sink.Sink sink, java.util.Loca…

### PR DESCRIPTION
**Pull request by agaengel**
…le locale) to avoid maven site error

### CODE REVIEW

**Comment by stoicflame** [comment]
I'm afraid this isn't going to work because `org.codehaus.doxia.sink.Sink` doesn't extend or implement `org.apache.maven.doxia.sink.Sink`.

**Comment by agaengel** [comment]
@stoicflame it's correct that it does not extend the method but it works just try with the test project

I think that some maven process checks via reflection if the method with the right signature is present

Regards
Alex

**Comment by fhm84** [comment]
Hi @stoicflame we just tested enunciate 2.17.1 on maven 3.9.5 (java 21) using maven-site-plugin:3.12.1 ... unfortunatelly, it didn't work, because of missing method exception. But we found a way to get it run (and from my point of view, this should also be backwards-compatible). Even if in the meanwhile `org.codehaus.doxia.sink.Sink` extends `org.apache.maven.doxia.sin.Sink`, I think we just could/should provide 2 generate-methods: one for each type. And by removing @Overwrite annotation, from my point of view, we might also be "safe" for the future ;) - especially, because currently this `sink` is not used within this method.

**Comment by stoicflame** [comment]
At a6f7fe9b7bc55fc7c8cb5e4dfa9d5a0282d8511d I implemented @fhm84 's suggestion. I haven't tested it on Maven 3.9.5 yet, though.

**Comment by fhm84** [comment]
Ok, cool. Thanks @stoicflame . As I already wrote, we tested this approach with maven 3.9.5 ;)

**Pull request closed without merging**
