### PR TITLE
Added support for jakarta.ws.rs and jakarta.validation

### PR DESCRIPTION
**Pull request by stasha**
Added support for jakarta.ws.rs, jakarta.validation and added examples/jakarta-jax-rs-jackson

### CODE REVIEW

**Comment by stoicflame** [comment]
This looks great. Thanks for the hard work and the PR! I plan to make a few adjustments to better support auto-detection and backwards compatibility before I merge.

**Comment by stasha** [comment]
Thanks and no problem :). Yes, please, feel free to improve it :+1:

**Comment by stoicflame** [comment]
Merged. Thanks again!

Had to add e48c3f759 to make sure jakarta annotations weren't _required_ as a dependency, but other than that I accepted it as-is.

**Comment by stasha** [comment]
Cool, thank you too!

**Comment by stoicflame** [comment]
Released in `2.14.0`.

**Pull request merged**
