### PR TITLE
Removed the description of non-artifact downloads

### PR DESCRIPTION
**Pull request by ncoe**
This should resolve a small part of #740

### CODE REVIEW

**Comment by stoicflame** [comment]
I'm not understanding the intent of this PR. Is it not valid to have a description for an "unattached" file download?

**Comment by ncoe** [comment]
When attaching a download, you have the description that can be specified for the bundle (which does render), and a description for each line item for the bundle (which is pulled presumably from the artifact description). The artifacts commonly seem to be the various clients that can be generated.
What I do not like is specifying some other kind of file, and having a description column that will always be blank.

image

Alternatively, being able to specify something for the highlighted description would be fine. What makes it odd is that you can overlook the fact that the description you specify in the `enunciate.xml` configuration is put in the header section when it can be expected in the description column.

Does this make sense?

**Comment by stoicflame** [comment]
I see.

So is the description more intuitive in the `description` column? Or under the header?

I think I tend to lean more towards the `description` column...

**Comment by ncoe** [comment]
As long as one is chosen over the other, it should not matter. Would you like me to update the pull request by moving the description to the column?

**Comment by stoicflame** [comment]
Yes, that would be great.

**Comment by ncoe** [comment]
Should I include a screenshot that shows what the layout is with the changes?

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).

**Pull request merged**
