### PR TITLE
Added JDK9 - JDK19 support

### PR DESCRIPTION
**Pull request by stasha**
This change enables building project using any JDK >= 1.8. 

Building should be easy as running: 
```
JAVA_HOME=/{path.to.java}/jdk-1.8 mvn clean install
JAVA_HOME=/{path.to.java}/jdk-19 mvn clean install
```

### CODE REVIEW

**Comment by stoicflame** [comment]
Thanks again. I'll review and merge ASAP.

**Comment by stasha** [comment]
:+1:

**Comment by stasha** [comment]
Yes, changes are to allow compiling with JDK >= 1.9 but also keep to work with 1.8 as before. 
I just pushed a change that should enable javac-support module to be built with JDK >= 1.9. Please take a look at latest commit.
Note that I did not add this change in every module as I was following  "fix what fails" path :).
The whole JDK >= 1.9 mechanism is actually run by `ant` that in turn runs `mvn` in forked java process passing new JDK arguments that are not supported by 1.8.
The ant-run plugin setup can be found in `enunciate-parent/pom.xml:894` . 

The process is next:
1. mvn clean install invokes ant-run specified in JDK9 profile that has `!env.loopback` 
2. ant-run sets all required JDK stuff and runs mvn clean install -Denv.loopback=true in forked java process
3. because !env.loopback is now set, maven ignores that profile and builds everything in expected way

It's quite a hack, but it preserves backward compatibility and it also works transparently in IDE just based on JDK version without a need for custom configurations. 

I'm aware it may be to hacky and complicated to include into official release, but as I was doing this for some of my future projects that will be on latest technologies I thought I'll share it with you, as you may find it also practicall supporting latest JDKs.

**Comment by stoicflame** [comment]
At 26cbca6228bea6a3404daa21af73bda6b4f7d071 I've applied these changes so it works without major updates with later Java versions.

**Pull request closed without merging**
