### PR TITLE
#476 Generate operations summary for Swagger files

### PR DESCRIPTION
**Pull request by vincent-zurczak**

### CODE REVIEW

**Comment by vincent-zurczak** [comment]
Wait, this may cause some problems when descriptions are quite long. We should rather only take the first sentence. I will update the PR.

**Comment by vincent-zurczak** [comment]
Done.
If the Javadoc only contains a sentence, it is picked up. If the first sentence is followed by a HTML tag or another sentence, we only use the first sentence. The other parts will appear in the implementation notes.

**Comment by stoicflame** [comment]
Lovely. Thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Pull request merged**
